language: scala
jdk: oraclejdk8
scala: 2.12.6

stages:
  - name: build
  - name: publish
    if: ((branch = master) AND (type != pull_request)) OR (tag IS present)
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script: sbt compile
    - stage: publish
      # release only on merge commits or tags
      script: if [[ "$(git rev-list --merges HEAD^..HEAD)" || "$TRAVIS_TAG" ]]; then sbt releaseEarly; else echo "skipping release"; fi
    - stage: release
      script: sbt githubRelease

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
